# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lh9EdLyykilUGs40i1zfW43eBpKjnQgF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import joblib
import zipfile

# Unzip the dataset
with zipfile.ZipFile('AEP_hourly.csv.zip', 'r') as zip_ref:
    zip_ref.extractall('./')

# Load the dataset
df = pd.read_csv('AEP_hourly.csv')

# Convert Datetime column to pandas datetime object
df['Datetime'] = pd.to_datetime(df['Datetime'])

# Sort chronologically and drop any duplicate timestamp entries
df = df.sort_values('Datetime').drop_duplicates(subset=['Datetime']).reset_index(drop=True)

# Set Datetime as index
df.set_index('Datetime', inplace=True)

print("Dataset Overview:")
print(df.head())

# Temporal features
df['hour'] = df.index.hour
df['dayofweek'] = df.index.dayofweek
df['dayofmonth'] = df.index.day
df['month'] = df.index.month
df['quarter'] = df.index.quarter
df['year'] = df.index.year
df['dayofyear'] = df.index.dayofyear

# Historical load features (Lags)
df['lag_1h'] = df['AEP_MW'].shift(1)            # Power load 1 hour ago
df['lag_24h'] = df['AEP_MW'].shift(24)          # Power load 24 hours ago
df['lag_1w'] = df['AEP_MW'].shift(24 * 7)       # Power load 1 week ago

# 24-hour rolling average load
df['rolling_mean_24h'] = df['AEP_MW'].shift(1).rolling(window=24).mean()

# Drop missing values created by shifting
df.dropna(inplace=True)

print(f"Total processed records: {len(df)}")

# Define features and target variable
features = ['hour', 'dayofweek', 'dayofmonth', 'month', 'quarter',
            'year', 'dayofyear', 'lag_1h', 'lag_24h', 'lag_1w', 'rolling_mean_24h']
target = 'AEP_MW'

# Split into train (before 2017) and test (2017 onwards)
train_df = df.loc[df.index < '2017-01-01']
test_df = df.loc[df.index >= '2017-01-01']

X_train, y_train = train_df[features], train_df[target]
X_test, y_test = test_df[features], test_df[target]

print(f"Training samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")

# Initialize and train the model
model = RandomForestRegressor(n_estimators=100, max_depth=15, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

# Predict on test data
y_pred = model.predict(X_test)

# Calculate performance metrics
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Root Mean Squared Error (RMSE): {rmse:.2f} MW")
print(f"Mean Absolute Error (MAE):     {mae:.2f} MW")
print(f"R² Score:                       {r2:.4f}")

plt.figure(figsize=(14, 6))

# Plotting first 14 days of predictions for visual clarity
sample_size = 24 * 14
plt.plot(y_test.index[:sample_size], y_test.values[:sample_size], label='Actual Load (MW)', color='blue', alpha=0.7)
plt.plot(y_test.index[:sample_size], y_pred[:sample_size], label='Predicted Load (MW)', color='orange', linestyle='--')

plt.title('AEP Smart Energy Load Prediction (First 2 Weeks of Test Data)')
plt.xlabel('Datetime')
plt.ylabel('Energy Consumption (MW)')
plt.legend()
plt.grid(True)
plt.show()

# Save model to disk
joblib.dump(model, 'aep_smart_energy_model.pkl')
print("Model saved as 'aep_smart_energy_model.pkl'")

!pip install -q streamlit
!npm install -g localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import joblib
# from datetime import datetime
# 
# # Load saved model
# @st.cache_resource
# def load_model():
#     return joblib.load('aep_smart_energy_model.pkl')
# 
# model = load_model()
# 
# st.set_page_config(page_title="Smart Energy Predictor", page_icon="⚡", layout="centered")
# 
# st.title("⚡ Smart Energy Consumption Predictor")
# st.write("Predict hourly electricity load (in MW) for AEP grid based on temporal parameters and historical load values.")
# 
# st.markdown("---")
# 
# # User Input Controls
# col1, col2 = st.columns(2)
# 
# with col1:
#     selected_date = st.date_input("Select Date", datetime(2018, 1, 1))
#     selected_time = st.time_input("Select Hour", datetime.now().time())
# 
# with col2:
#     lag_1h = st.number_input("Power Load 1h ago (MW)", value=15000.0, step=100.0)
#     lag_24h = st.number_input("Power Load 24h ago (MW)", value=14800.0, step=100.0)
# 
# lag_1w = st.number_input("Power Load 1 week ago (MW)", value=15200.0, step=100.0)
# rolling_mean_24h = st.number_input("24-Hour Average Load (MW)", value=15050.0, step=100.0)
# 
# # Extract features from selected date/time
# hour = selected_time.hour
# dayofweek = selected_date.weekday()
# dayofmonth = selected_date.day
# month = selected_date.month
# quarter = (month - 1) // 3 + 1
# year = selected_date.year
# dayofyear = selected_date.timetuple().tm_yday
# 
# if st.button("Predict Energy Demand", use_container_width=True):
#     # Construct feature dataframe matching model inputs
#     input_data = pd.DataFrame([[
#         hour, dayofweek, dayofmonth, month, quarter,
#         year, dayofyear, lag_1h, lag_24h, lag_1w, rolling_mean_24h
#     ]], columns=[
#         'hour', 'dayofweek', 'dayofmonth', 'month', 'quarter',
#         'year', 'dayofyear', 'lag_1h', 'lag_24h', 'lag_1w', 'rolling_mean_24h'
#     ])
# 
#     prediction = model.predict(input_data)[0]
# 
#     st.success(f"### Predicted Energy Load: **{prediction:,.2f} MW**")

!curl https://loca.lt/mytunnelpassword

!streamlit run app.py & npx localtunnel --port 8501

